/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as AboutImport } from './routes/about'
import { Route as ImageGallaryImport } from './routes/Image-gallary'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const ImageGallaryRoute = ImageGallaryImport.update({
  id: '/Image-gallary',
  path: '/Image-gallary',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/Image-gallary': {
      id: '/Image-gallary'
      path: '/Image-gallary'
      fullPath: '/Image-gallary'
      preLoaderRoute: typeof ImageGallaryImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Image-gallary': typeof ImageGallaryRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Image-gallary': typeof ImageGallaryRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/Image-gallary': typeof ImageGallaryRoute
  '/about': typeof AboutRoute
  '/home': typeof HomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Image-gallary' | '/about' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Image-gallary' | '/about' | '/home'
  id: '__root__' | '/' | '/Image-gallary' | '/about' | '/home'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageGallaryRoute: typeof ImageGallaryRoute
  AboutRoute: typeof AboutRoute
  HomeRoute: typeof HomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageGallaryRoute: ImageGallaryRoute,
  AboutRoute: AboutRoute,
  HomeRoute: HomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/Image-gallary",
        "/about",
        "/home"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/Image-gallary": {
      "filePath": "Image-gallary.jsx"
    },
    "/about": {
      "filePath": "about.jsx"
    },
    "/home": {
      "filePath": "home.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
