/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HomeImport } from './routes/home'
import { Route as IndexImport } from './routes/index'
import { Route as ImageGalleryIndexImport } from './routes/image-gallery/index'
import { Route as UserUserImport } from './routes/user/user'
import { Route as UserProfileImport } from './routes/user/profile'
import { Route as ImageGalleryImgIdImport } from './routes/image-gallery/$imgId'

// Create Virtual Routes

const PostLazyImport = createFileRoute('/post')()

// Create/Update Routes

const PostLazyRoute = PostLazyImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/post.lazy').then((d) => d.Route))

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ImageGalleryIndexRoute = ImageGalleryIndexImport.update({
  id: '/image-gallery/',
  path: '/image-gallery/',
  getParentRoute: () => rootRoute,
} as any)

const UserUserRoute = UserUserImport.update({
  id: '/user/user',
  path: '/user/user',
  getParentRoute: () => rootRoute,
} as any)

const UserProfileRoute = UserProfileImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRoute,
} as any)

const ImageGalleryImgIdRoute = ImageGalleryImgIdImport.update({
  id: '/image-gallery/$imgId',
  path: '/image-gallery/$imgId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/post': {
      id: '/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof PostLazyImport
      parentRoute: typeof rootRoute
    }
    '/image-gallery/$imgId': {
      id: '/image-gallery/$imgId'
      path: '/image-gallery/$imgId'
      fullPath: '/image-gallery/$imgId'
      preLoaderRoute: typeof ImageGalleryImgIdImport
      parentRoute: typeof rootRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileImport
      parentRoute: typeof rootRoute
    }
    '/user/user': {
      id: '/user/user'
      path: '/user/user'
      fullPath: '/user/user'
      preLoaderRoute: typeof UserUserImport
      parentRoute: typeof rootRoute
    }
    '/image-gallery/': {
      id: '/image-gallery/'
      path: '/image-gallery'
      fullPath: '/image-gallery'
      preLoaderRoute: typeof ImageGalleryIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/post': typeof PostLazyRoute
  '/image-gallery/$imgId': typeof ImageGalleryImgIdRoute
  '/user/profile': typeof UserProfileRoute
  '/user/user': typeof UserUserRoute
  '/image-gallery': typeof ImageGalleryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/post': typeof PostLazyRoute
  '/image-gallery/$imgId': typeof ImageGalleryImgIdRoute
  '/user/profile': typeof UserProfileRoute
  '/user/user': typeof UserUserRoute
  '/image-gallery': typeof ImageGalleryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/post': typeof PostLazyRoute
  '/image-gallery/$imgId': typeof ImageGalleryImgIdRoute
  '/user/profile': typeof UserProfileRoute
  '/user/user': typeof UserUserRoute
  '/image-gallery/': typeof ImageGalleryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/post'
    | '/image-gallery/$imgId'
    | '/user/profile'
    | '/user/user'
    | '/image-gallery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/post'
    | '/image-gallery/$imgId'
    | '/user/profile'
    | '/user/user'
    | '/image-gallery'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/post'
    | '/image-gallery/$imgId'
    | '/user/profile'
    | '/user/user'
    | '/image-gallery/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  PostLazyRoute: typeof PostLazyRoute
  ImageGalleryImgIdRoute: typeof ImageGalleryImgIdRoute
  UserProfileRoute: typeof UserProfileRoute
  UserUserRoute: typeof UserUserRoute
  ImageGalleryIndexRoute: typeof ImageGalleryIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  PostLazyRoute: PostLazyRoute,
  ImageGalleryImgIdRoute: ImageGalleryImgIdRoute,
  UserProfileRoute: UserProfileRoute,
  UserUserRoute: UserUserRoute,
  ImageGalleryIndexRoute: ImageGalleryIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/home",
        "/post",
        "/image-gallery/$imgId",
        "/user/profile",
        "/user/user",
        "/image-gallery/"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/home": {
      "filePath": "home.jsx"
    },
    "/post": {
      "filePath": "post.lazy.jsx"
    },
    "/image-gallery/$imgId": {
      "filePath": "image-gallery/$imgId.jsx"
    },
    "/user/profile": {
      "filePath": "user/profile.jsx"
    },
    "/user/user": {
      "filePath": "user/user.jsx"
    },
    "/image-gallery/": {
      "filePath": "image-gallery/index.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
